//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSServerReadyLauncher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PackageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PackageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSServerReadyLauncher.PackageResources", typeof(PackageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VSServerReadyLauncher was unable to launch project &apos;{0}&apos;. {1}
        ///
        ///To configure launch settings, open the configuration file..
        /// </summary>
        internal static string Err_ProjectDebugFailed_Args2 {
            get {
                return ResourceManager.GetString("Err_ProjectDebugFailed_Args2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VSServerReadyLauncher was unable to launch project &apos;{0}&apos;. No debuggable configuration can be found.
        ///
        ///To configure launch settings, open the configuration file..
        /// </summary>
        internal static string Err_ProjectNotDebuggable_Args1 {
            get {
                return ResourceManager.GetString("Err_ProjectNotDebuggable_Args1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VSServerReadyLauncher was unable to parse configuration file &apos;{0}&apos;. Unable to find specified project &apos;{1}&apos; in the current solution. .
        /// </summary>
        internal static string Err_UnableToFindProject_Args2 {
            get {
                return ResourceManager.GetString("Err_UnableToFindProject_Args2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VSServerReadyLauncher was unable to parse configuration file &apos;{0}&apos;. Unable to parse regular expression pattern &apos;{1}&apos;.
        ///
        ///{2}.
        /// </summary>
        internal static string Err_UnableToParsePattern_Args3 {
            get {
                return ResourceManager.GetString("Err_UnableToParsePattern_Args3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VSServerReadyLauncher was unable to parse configuration file &apos;{0}&apos;.
        ///
        ///{1}.
        /// </summary>
        internal static string Err_UnableToParseSettingsFile_Args2 {
            get {
                return ResourceManager.GetString("Err_UnableToParseSettingsFile_Args2", resourceCulture);
            }
        }
    }
}
